### ISSUE TITLE
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates.

### ISSUE THREAD

**Issue by LuisText** [flathub/media.emby.EmbyServer#2]
Hello.

org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Applications using this runtime:
   media.emby.EmbyServer

Please update.

**Comment by alucryd** [comment]
Fixed via 1e91a4084d48850d863b6260b5e8216af80c7ea4. Thanks for the heads up!
